[package]
name = "tlsn-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "tlsn_core"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tlsn-tls-core = { path = "../tls-core" }
