[package]
name = "tlsn-tls-core"
version = "0.1.0"
edition = "2018"

[lib]
name = "tls_core"

[features]
default = ["logging", "tls12"]
tls12 = []
handshake = []
ghash = []
logging = ["tracing"]

[dependencies]
rand = "0.8.5"
sct = "0.7.0"
webpki = { version = "0.22.0", features = ["alloc", "std"] }
tracing = { version = "0.1.34", optional = true }
elliptic-curve = { version = "0.11.12" }
ring = "0.16.20"

[dev-dependencies]
criterion = "0.3.5"
hex = "0.4"
