[package]
name = "tlsn-tls-2pc-aio"
version = "0.1.0"
edition = "2021"

[lib]
name = "tls_2pc_aio"

[dependencies]
async-trait = "0.1.56"
thiserror = "1.0.30"
tlsn-tls-core = { path = "../tls-core" }
